#ifndef AI_HARD_H
#define AI_HARD_H
CARD AI_HARD(CARDSET *,CARDSET *,STATE,CARDSET,CARDSET);
CARD Project1(CARDSET *,CARDSET *,STATE,CARDSET,CARDSET);
CARD Project2(CARDSET *,CARDSET *,STATE,CARDSET,CARDSET);

int getPreviousPlayer(STATE);
CARD Analyze(CARDSET,CARDSET,CARDSET *,STATE);
int * countColor(CARDSET);
#endif